# Cyber Fraud Detection System – Data Cleaning

## Objective
This notebook performs:
- Data loading
- Data understanding
- Data cleaning
- Missing value handling
- Duplicate removal
- Data type conversion
- Basic feature engineering
- Exporting cleaned dataset

Tech Stack:
- Python
- Pandas
- NumPy

In [2]:
import pandas as pd
import numpy as np

# Display settings
pd.set_option('display.max_columns', None)

## Load Dataset

In [3]:
# Load dataset
data = pd.read_csv('../data/raw/credit_card_fraud_raw.csv')

# Preview dataset
data.head()

,transaction_id,amount,transaction_hour,merchant_category,foreign_transaction,location_mismatch,device_trust_score,velocity_last_24h,cardholder_age,is_fraud
0,1,84.47,22,Electronics,0,0,66,3,40,0
1,2,541.82,3,Travel,1,0,87,1,64,0
2,3,237.01,17,Grocery,0,0,49,1,61,0
3,4,164.33,4,Grocery,0,1,72,3,34,0
4,5,30.53,15,Food,0,0,79,0,44,0

## Dataset Overview

In [4]:
# Shape of dataset
print("Dataset Shape:", data.shape)

# Column names
print("\nColumns:")
print(data.columns)

# Dataset information
print("\nDataset Info:")
data.info()

Dataset Shape: (10000, 10)

Columns:
Index(['transaction_id', 'amount', 'transaction_hour', 'merchant_category',
       'foreign_transaction', 'location_mismatch', 'device_trust_score',
       'velocity_last_24h', 'cardholder_age', 'is_fraud'],
      dtype='object')

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   transaction_id       10000 non-null  int64
 1   amount               10000 non-null  float64
 2   transaction_hour     10000 non-null  int64
 3   merchant_category    10000 non-null  object
 4   foreign_transaction  10000 non-null  int64
 5   location_mismatch    10000 non-null  int64
 6   device_trust_score   10000 non-null  int64
 7   velocity_last_24h    10000 non-null  int64
 8   cardholder_age       10000 non-null  int64
 9   is_fraud             10000 non-null  int64
dtypes: float64(1), int64(8), object(1)
memory usage: 781.4+ KB

## Check Missing Values

In [5]:
# Missing values
missing_values = data.isnull().sum()

missing_values[missing_values > 0]

Series([], dtype: int64)

## Handle Missing Values

In [6]:
# Example missing value handling

# Numerical columns
num_cols = data.select_dtypes(include=['int64', 'float64']).columns

for col in num_cols:
    data[col].fillna(data[col].median(), inplace=True)

# Categorical columns
cat_cols = data.select_dtypes(include=['object']).columns

for col in cat_cols:
    data[col].fillna(data[col].mode()[0], inplace=True)

print("Missing values handled successfully.")

Missing values handled successfully.

C:\Users\majum\AppData\Local\Temp\ipykernel_1416\798171614.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
C:\Users\majum\AppData\Local\Temp\ipykernel_1416\798171614.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].mode()[0], inplace=True)

## Check Duplicate Records

In [7]:
# Duplicate rows
print("Duplicate Rows:", data.duplicated().sum())

Duplicate Rows: 0

## Remove Duplicates

In [8]:
# Remove duplicates
data.drop_duplicates(inplace=True)

print("Duplicates removed successfully.")
print("New Shape:", data.shape)

Duplicates removed successfully.
New Shape: (10000, 10)

## Data Type Conversion

In [9]:
# Convert transaction_time column to datetime if present
if 'transaction_time' in data.columns:
    data['transaction_time'] = pd.to_datetime(data['transaction_time'])

print(data.dtypes)

transaction_id           int64
amount                 float64
transaction_hour         int64
merchant_category       object
foreign_transaction      int64
location_mismatch        int64
device_trust_score       int64
velocity_last_24h        int64
cardholder_age           int64
is_fraud                 int64
dtype: object

## Basic Statistical Summary

In [10]:
# Statistical summary
data.describe()

,transaction_id,amount,transaction_hour,foreign_transaction,location_mismatch,device_trust_score,velocity_last_24h,cardholder_age,is_fraud
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5000.50000,175.949849,11.593300,0.097800,0.085700,61.798900,2.008900,43.468700,0.015100
std,2886.89568,175.392827,6.922708,0.297059,0.279935,21.487053,1.432559,14.979147,0.121957
min,1.00000,0.000000,0.000000,0.000000,0.000000,25.000000,0.000000,18.000000,0.000000
25%,2500.75000,50.905000,6.000000,0.000000,0.000000,43.000000,1.000000,30.000000,0.000000
50%,5000.50000,122.095000,12.000000,0.000000,0.000000,62.000000,2.000000,44.000000,0.000000
75%,7500.25000,242.480000,18.000000,0.000000,0.000000,80.000000,3.000000,56.000000,0.000000
max,10000.00000,1471.040000,23.000000,1.000000,1.000000,99.000000,9.000000,69.000000,1.000000

## Feature Engineering

In [11]:
# Create transaction hour feature
if 'transaction_time' in data.columns:
    data['transaction_hour'] = data['transaction_time'].dt.hour

# High amount flag
if 'amount' in data.columns:
    threshold = data['amount'].quantile(0.95)
    data['high_amount_flag'] = np.where(data['amount'] > threshold, 1, 0)

print("Feature engineering completed.")

Feature engineering completed.

## Outlier Detection

In [12]:
# Detect outliers using IQR method

if 'amount' in data.columns:
    Q1 = data['amount'].quantile(0.25)
    Q3 = data['amount'].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = data[(data['amount'] < lower_bound) | 
                    (data['amount'] > upper_bound)]

    print("Number of Outliers:", outliers.shape[0])

Number of Outliers: 501

## Final Dataset Check

In [16]:
# Final dataset preview
data.head()

(10000, 11)

## Export Cleaned Dataset

In [14]:
# Save cleaned dataset
data.to_csv('cleaned_fraud_data.csv', index=False)

print("Cleaned dataset exported successfully.")

Cleaned dataset exported successfully.

# Next Steps

After this notebook:
1. Perform Exploratory Data Analysis (EDA)
2. Create SQL tables
3. Train Machine Learning models
4. Build Tableau Dashboard
5. Deploy using Streamlit